name: Build and Publish Python Package

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.6'  # Specify Python 3.6 here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  # Install build for building the package

    - name: Build package
      run: |
        python -m build  # Builds the package using pyproject.toml

    - name: Publish package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
      run: |
        pip install twine
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u __token__ -p $GITHUB_TOKEN
