name: Build and Publish Python Package and Documentation

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-20.04  # Use an appropriate Ubuntu version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build sphinx twine

    - name: Build package
      run: |
        python -m build

    - name: Publish package to GitHub Packages
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        pip install twine
        twine upload --verbose --repository-url https://nuget.pkg.github.com/ljf441/index.json dist/* -u ${{ github.actor }} -p $MY_GITHUB_TOKEN
