name: Build and Publish Python Package and Documentation

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-20.04  # Use an appropriate Ubuntu version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build sphinx

    - name: Build package
      run: |
        python -m build

    - name: Publish package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
      run: |
        pip install twine
        twine upload --repository-url https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json dist/* -u ${{ github.actor }} -p $GITHUB_TOKEN